export enum Topics {
  AccountingAndFinance = 'Accounting And Finance',
  ArtificialIntelligence = 'Artificial Intelligence',
  Paperless = 'Paperless',
  Chatgpt = 'Chatgpt',
  MachineLearning = 'Machine Learning',
  Cybersecurity = 'Cybersecurity',
  BlockchainTechnology = 'Blockchain Technology',
  AutomatedWorkflow = 'Automated Workflow',
  BusinessStrategy = 'Business Strategy',
  Cloud = 'Cloud',
  Compliance = 'Compliance',
  CustomerSupport = 'Customer Support',
  DigitalTransformation = 'Digital Transformation',
  DocumentManagement = 'Document Management',
  RemoteWork = 'Remote Work',
  HumanResources = 'Human Resources',
  Integration = 'Integration',
  Productivity = 'Productivity',
  OpenSource = 'Open Source',
  WebScraping = 'Web Scraping',
  Server = 'Server',
  SoftwareDevelopment = 'Software Development',
  SalesAndMarketing = 'Sales And Marketing',
  ProjectManagement = 'Project Management',
}
